query Cart($input: GetCartInput!){
  cart(input: $input){
    id
    userId
    orderId
    status
    externalUserId
    cartItems {
      barcode { barcode, coverImage, sku, category, priceBase, priceSale, stock, size, product { title, description }  }
      price,
      quantity
      currency
    }
    totalAmount
    totalItemsCount
    createdAt
    updatedAt
  }
}