query ReviewsList($input: FilterReviewInput!){
  reviews(input: $input){
    id, sku, skuFamily, reviewAuthor, reviewText, reviewDate,reviewRating, reviewAnswer, createdAt, product { sku, coverImage }
  }
}